### ISSUE TITLE
A blank math cell chould not be a syntax error.

### ISSUE THREAD

**Issue by VanHulleOne** [mgreminger/EngineeringPaper.xyz#160]
Hopefully this is an easy one but currently a blank math cell produces a syntax error and it would feel nicer if it did not. When you add a new cell and are thinking about what you want to write I find it hard on the brain to be scolded for a syntax error before you've even done any work. I prefer syntax checkers that provide a few seconds before they start complaining to me while I am actively typing but that is probably more work than is needed at this moment. For now, simply having the syntax checker ignore blank cells would be appreciated.

**Comment by mgreminger** [comment]
Yes, it makes sense to allow a blank cell without a syntax error. Including a delay is a little bit more complicated, as you point out. Probably doable with a CSS transition since I need to keep the underlying logic the same so that I'm not sending code with a syntax error to the solver.
