### ISSUE TITLE
Significant Figures

### ISSUE THREAD

**Issue by JWock82** [mgreminger/EngineeringPaper.xyz#177]
First of all, thank you for this great project. I am really enjoying it. Thanks also for your quick response to the last issue I opened too. The new improvements work great!

Is there a way to control the number of decimals displayed? In this case only 2 significant figures really matter:

![image](https://github.com/mgreminger/EngineeringPaper.xyz/assets/33323539/a45a2162-386a-48bc-860e-e43f86e131e4)

**Comment by mgreminger** [comment]
Thanks for the feedback and I'm glad to hear the new improvements are working well.
Yes, being able to set the significant figures would be useful to make the results easier to read. I'll start thinking of the best way to implement the UI for this.
