### ISSUE TITLE
Application not compatible with European(ISO) keyboards.

### ISSUE THREAD

**Issue by beltet** [mgreminger/EngineeringPaper.xyz#184]
Hi.
Seems like the application isn't compatible with ISO keyboards.
When you try to type legend 'greater than/lesser than and equal to' it dosen't autotranslate to the legend when you type '<=' or '>='.
When you type '<' or '>' it gives a '/' on first keypress. This is due to that ANSI layout translate that extra ISO key to '/'. But on the second keypress it gives the right symbol(but still dosen't autotranslate).

I've tried US ANSI keyboard aswell, and it works as it should.

The machine I use have this setup:
Windows 10 Pro
American English language
Swedish+American keyboard
Tested both with ANSI and ISO Swedish keyboard.

Also tested on Pop !OS(ubuntu derivate) with same result.

**Comment by mgreminger** [comment]
Thanks for the bug report. I've been trying to replicate the issue by using a Swedish keyboard layout in Ubuntu but I have not been able to reproduce the problem. My keyboard doesn't have the greater than/less than key next to the left shift but I'm able to type the greater than and less than symbols using RightAlt+LeftShift+Z  for `<` and RightAlt+LeftShift+X for `>` using the keyboard layout pictured below. When I use these key combinations, it is working correctly. Is the issue with the key next to the left shift? Does your layout allow you to use the Z and X key combinations?

![swedish_keyboard](https://github.com/mgreminger/EngineeringPaper.xyz/assets/6439649/41aba0a7-55e1-4eb8-95e1-0677ea361046)

There's an older version of EngineeringPaper.xyz that uses a different math editor component. Could you try [classic.engineeringpaper.xyz](https://classic.engineeringpaper.xyz) to see if you have the same issue with the different math editor component?

I'm assuming the greater than and less then symbol are working properly when you type into a documentation cell in EngineeringPaper.xyz?

It's strange that its showing a forward slash, the forward slash should be automatically converted into a fraction. Is the dashed vertical line `¦` turning into the forward slash?

**Comment by beltet** [comment]
Hi! Thanks for the reply.
I think I wasn't clear enough(maybe due not knowing unicode character name).
The problem is that you cant type '>' + '=' and its translates to '≥'.
So 'Greater than' + 'equals to' translates to 'Greater than or equals to'.
This works using American English(And American English with intl. dead keys, that I'm using on my laptop).
But it doesn't work using Swedish layout.


> Is the issue with the key next to the left shift?

Yes. Its a specific ISO key. And when using that ISO specific key with American English layout, in a regular text editor, it translates to backslash(\). Not forwardslash(/) as I told you before. Sorry for that.


> Could you try [classic.engineeringpaper.xyz](https://classic.engineeringpaper.xyz) to see if you have the same issue with the different math editor component?

I will a little bit later and report back.


> It's strange that its showing a forward slash, the forward slash should be automatically converted into a fraction. Is the dashed vertical line `¦` turning into the forward slash?

I think it's due the software assumes a ANSI keyboard but then "realizes" it is a ISO one? But I'm not a programmer...
And a correction again, it was not forward slash, it was a backward.
And a note as well. On SWE ISO its just a regular vertical line. There are different depending on what ISO language you have. I believe that UK ISO uses the dashed vertical line. Yeah... It's confusing...

**Comment by mgreminger** [comment]
There haven't been any updates on this one for a little while so I'm assuming it's not EngineeringPaper.xyz related. If the issue is still EngineeringPaper.xyz related, post a comment here and I'll re-open the issue.
