### ISSUE TITLE
Syntax error when trying to specify result unit after an equation

### ISSUE THREAD

**Issue by prostolyubo** [mgreminger/EngineeringPaper.xyz#185]
Let's assume:
`a = 5 [mm]`
`b = 2 [mm]`
This **does work**:
`test = a + b =`
This does **not work**:
`test = a + b = [mm]`

As a user' I would like to be able to specify the result units of equation inline instead of writing two separate lines of code:
`test = a + b`
`test = [mm]`

**Comment by mgreminger** [comment]
Thanks for the bug report. Yes, it should work to specify units for a combined assignment-query. I'm not able to reproduce the issue on my end (see the screenshot below). Here's a link to a [sheet where it's working](https://engineeringpaper.xyz/8sx9AEFNvZtjpD9GHoxVZn). Could you share a link to a sheet where you're able to reproduce this issue?

![Screenshot from 2023-06-02 12-07-58](https://github.com/mgreminger/EngineeringPaper.xyz/assets/6439649/ff50d32d-7d86-4734-97dc-a30bb46642e0)

**Comment by prostolyubo** [comment]
I already modified the file to remove the broken sentence. Now I tried rewriting it and it indeed works. I am really sorry, perhaps there was something else in the equation that broke it and made me think this is impossible.

**Comment by mgreminger** [comment]
Thanks for the update. No problem, it makes sense that this could be confused since the "Syntax Error" error message is kind of a catch all that can have many causes.
