### ISSUE TITLE
Self hosting

### ISSUE THREAD

**Issue by mercurial-moon** [mgreminger/EngineeringPaper.xyz#194]
Is there a guide to build a self hosted `EngineeringPaper` server.

I see that on the main page
```# Build the production version of the site
npm run build
```
However additionally this also is mentioned 
```
These instructions are only needed to create a development environment for [EngineeringPaper.xyz](https://engineeringpaper.xyz/). To run the app, simply go to EngineeringPaper.xyz.
```
would the npm build command suffice to get a self hosted server up and running?

**Comment by mgreminger** [comment]
Once you run `npm run build`, the contents of the `./public` directory can be hosted as a static website.

**Comment by mgreminger** [comment]
Closing as resolved, feel free to add more comments if there are any additional questions.
