### ISSUE TITLE
[Feature request] Export to PDF

### ISSUE THREAD

**Issue by ltroj** [mgreminger/EngineeringPaper.xyz#215]
First of all - thanks for maintaining this project, I just started out with it and i love the ease of use.

As a completely new user I was confused about the lack of export features. Some googling showed me that it's intended to "Print to PDF" but this doesn't work well for me on Firefox. I would love to have a native "Export to PDF" feature that gives me consistent results.

Even an "Export to Markdown" feature which would allow to export the output to a plain text file in the form of 

```markdown
# heading 1
$\alpha = \beta$

[an image](image.png)

Lorem Ipsum
- - -
```
would be immensely helpful since that would allow to convert to pdf, html, latex, whatever.

Thanks again!

**Comment by mgreminger** [comment]
I would be interested in knowing what issues your are seeing printing from Firefox since it's the intention to fully support printing using the browsers builtin print mechanism. Generating a PDF (without using the browsers print functionality) or creating a markdown file would be fairly involved to implement and are likely a ways off.  I'm trying to leverage the browsers builtin capabilities as much as possible to be able to put energy into the usability and core features of the software.

**Comment by ltroj** [comment]
I see. This is how the Equation Solving sample turns out when saving to PDF from FF 119.0.1 (Windows):

[EngineeringPaper.xyz Equation Solving.pdf](https://github.com/mgreminger/EngineeringPaper.xyz/files/13402815/EngineeringPaper.xyz.Equation.Solving.pdf)

The problem might be add-on related, though - will have to test with a clean Firefox profile. Another problem is that my work machine is configured in a way that I can't even access the Firefox printing dialog but it directly opens the system's printing dialog so I don't even have the native Firefox PDF Export feature available. Both things have nothing to do with EP.xyz but require the user to trace down the problem and do some debugging which might be a practical problem for some.

Thanks again for the great tool!

**Comment by mgreminger** [comment]
Thanks for sharing the pdf showing the printing issues. If you close the side menu before printing, that will fix the printing issues that you're see. This is something I'll take a look at to see if this situation can be handled automatically in the future.

**Comment by mgreminger** [comment]
I just rolled out a fix for the Firefox printing bug you pointed out, thanks again for raising the issue. I'll keep this issue open since this fix doesn't address your file export feature request.

**Comment by mgreminger** [comment]
@ltroj Thanks for the suggestion of using Markdown as a conversion format. Using this approach, Markdown, Word Doc, and PDF export have been rolled out.

**Comment by ltroj** [comment]
Fantastic, i just got to test it and it works like a charm. Thanks for implementing this feature @mgreminger
