### ISSUE TITLE
[Feature Request] Latex Keyboard Shortcuts

### ISSUE THREAD

**Issue by memtech3** [mgreminger/EngineeringPaper.xyz#239]
Many math related softwares allow you to enter latex like shortcodes for symbols that automatically get converted into the symbols

**Comment by memtech3** [comment]
Thanks! I'll keep an eye out for this, if you close this can I reopen it later if I find any missing?

**Comment by mgreminger** [comment]
Yes, you can reopen the issue if you see an instance where an expression cannot be entered using the keyboard. You can also create a new issue, either way will work.
