### ISSUE TITLE
Units after a power causes a syntax error

### ISSUE THREAD

**Issue by VanHulleOne** [mgreminger/EngineeringPaper.xyz#247]
Putting units directly after a power (not in the power but after) causes a syntax error.
`J=3*10^6[m]` Does not work.
Both `J=10^6*3[m]` and `J=3*10^6*1[m]` work as expected.

I know it is not an easy task but more descriptive error messages would be nice. Took me a bit to figure out what was the problem this time.

Thanks again for the great at ever improving product!

**Comment by mgreminger** [comment]
Thanks for the issue report. Yes, I agree that this can be confusing. It's in the plans to implement this eventually, not sure on the time frame.
