### ISSUE TITLE
Feature request. Importing csv, or excel sheets.

### ISSUE THREAD

**Issue by swopnil123** [mgreminger/EngineeringPaper.xyz#252]
Is there a way to import data in the form of CSV or any other format?
It would be great if this feature is available. This together with the vectors and matrices will make it a total beast.

**Comment by mgreminger** [comment]
It's not possible to import tabular data at this time. There are plans to eventually make this possible. However, the UI changes required to make this functionality useful and intuitive is fairly involved in will take a while to implement.
